### ISSUE TITLE
fuel > 1

### ISSUE THREAD

**Issue by kai-sn-harris** [Lukas-cag/Python-Space-Ship-Sim#1]
https://github.com/Lukas-cag/Python-Space-Ship-Sim/blob/20e9d6af506a6b11c6de608aa1edb12b82602d6f/main.py#L31

Checking if the fuel is greater than 1 probably isnt the best bet. Not sure if it changes somewhere else in the code (it shouldn't) i would change it to:
`if self.__spaceshipPetrolLevel > 0 and self.__spaceshipY < 30:`
or
`if self.__spaceshipPetrolLevel >= 1 and self.__spaceshipY < 30:`

**Comment by Lukas-cag** [comment]
Oh yes thanks I think that was a mistake.
